name: few-shot-dt-instantiation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - pypdf
  - pytest
  - pytorch
  - pytorch-cuda=12.1
