"""Public reporting API.

``generate`` is the released, weight-free Level-B entry point. The current
manuscript Figure 5 is generated by :mod:`reporting.overall_performance`, and
data-driven Fig. 6--12 live in :mod:`reporting.final_figures`.
"""

from .frozen import generate

__all__ = ["generate"]
